import React from "react";
import { AdminHeader } from "@/components/admin/admin-header";
import { EmptyState } from "@/components/ui/empty-state";
import { BarChart3 } from "lucide-react";

export default function AdminAnalyticsPage() {
  return (
    <div className="space-y-6">
      <AdminHeader
        title="Visitor Analytics & Chat Insights"
        description="Daily digests generated by the Analytics Agent summarizing traffic, Recruiter Mode views, and chat queries."
      />

      <EmptyState
        title="No analytics recorded"
        description="Visitor tracking and chat conversation digests will appear here once the public site receives traffic."
        icon={<BarChart3 className="w-8 h-8 opacity-80" />}
      />
    </div>
  );
}
