"""
Connector Interface and Protocol Definition.
Sourced strictly from NOVA_01_System_Architecture.md §7.

NOTE: Per specification, X / Twitter is permanently excluded from this system.
"""

from typing import Protocol, List, Dict, Any, Optional
from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class RawItem:
    """Raw payload retrieved from an external platform connector."""
    external_id: str
    platform: str
    payload: Dict[str, Any]
    captured_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class DraftChange:
    """Proposed entity change generated by a connector or agent."""
    entity_type: str
    entity_id: Optional[str]
    diff: Dict[str, Any]
    ai_rationale: str


class Connector(Protocol):
    """
    Standard interface that all external data connectors must satisfy.
    Connectors only ingest and produce draft changes; they NEVER write to live tables.
    """
    name: str

    def fetch(self) -> List[RawItem]:
        """Fetch raw items from external source."""
        ...

    def to_draft(self, item: RawItem) -> DraftChange:
        """Convert a raw item into a proposed DraftChange for the approval queue."""
        ...
